#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

GREEN='\033[0;32m'
NOCOLOR='\033[0m'

echo "${GREEN}Starting pre-commit hook${NOCOLOR}"

echo "${GREEN}### Linting...${NOCOLOR}"
yarn lint

echo "${GREEN}### Auditing dependancies...${NOCOLOR}"
yarn audit

echo "${GREEN}Finished pre-commit hook${NOCOLOR}"